[actions.nd]
fill = false

[netif.veth0.1]
ip = "2001:db8::1"
proto = 6
port = 23

[backend.1_0]
ip = "2001:db8::2:2"
options = ["redirect", "dsr_l3", "src_ip=2001:db8::2:1", "alt_addr=2001:db8::2:3"]

[netif.veth0.2]
ip = "2001:db8::1"
proto = 17
port = 23

[backend.2_0]
ip = "2001:db8::2:2"
options = ["redirect", "dsr_l3", "src_ip=2001:db8::2:1", "alt_addr=2001:db8::2:3"]

[netif.veth0.3]
ip = "2001:db8::0:1"
proto = 58

[backend.3_0]
ip = "2001:db8::2:2"
options = ["redirect", "dsr_l3", "src_ip=2001:db8::2:1", "alt_addr=2001:db8::2:3"]

[netif.veth0.4]
ip = "10.0.0.1"
proto = 6
port = 23

[backend.4_0]
ip = "2001:db8::2:2"
options = ["redirect", "dsr_l3", "src_ip=2001:db8::2:1", "alt_addr=2001:db8::2:3"]

[netif.veth0.5]
ip = "10.0.0.1"
proto = 17
port = 23

[backend.5_0]
ip = "2001:db8::2:2"
options = ["redirect", "dsr_l3", "src_ip=2001:db8::2:1", "alt_addr=2001:db8::2:3"]

[netif.veth2.6]
ip = "10.0.0.1"
proto = 1

[backend.6_0]
ip = "2001:db8::2:2"
options = ["redirect", "dsr_l3", "src_ip=2001:db8::2:1", "alt_addr=2001:db8::2:3"]

